In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
b = np.array([[1, 2], [3, 4]]) 
print("2-D array",b)

2-D array [[1 2]
 [3 4]]


In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [27]:
b.shape
b.reshape(1,4)

array([[1, 2, 3, 4]])

In [29]:
b.shape

(2, 2)

In [37]:
c = np.dot(b,np.ones((2,2)))
print(c)

[[3. 3.]
 [7. 7.]]


In [35]:
np.sum(c)

20.0

In [36]:
c.T

array([[3., 7.],
       [3., 7.]])

In [48]:
np.random.randint(0,20,3)

array([2, 4, 5])

#inverse , determinent , eigenValues and eigenVectors

In [ ]:

print(c)

[[3. 3.]
 [7. 7.]]


In [ ]:
np.linalg.det(c)

-1.1657341758564124e-15

In [55]:
np.linalg.inv(c)

array([[-6.0047995e+15,  2.5734855e+15],
       [ 6.0047995e+15, -2.5734855e+15]])

In [56]:
np.linalg.eig(c)

EigResult(eigenvalues=array([ 0., 10.]), eigenvectors=array([[-0.70710678, -0.3939193 ],
       [ 0.70710678, -0.91914503]]))

In [57]:
newArr= np.array([[1,4,8],[2,5,6 ],[3,8,1]])
print(newArr)

[[1 4 8]
 [2 5 6]
 [3 8 1]]


In [58]:
np.linalg.det(newArr)

28.99999999999999

In [59]:
np.linalg.inv(newArr)

array([[-1.48275862,  2.06896552, -0.55172414],
       [ 0.55172414, -0.79310345,  0.34482759],
       [ 0.03448276,  0.13793103, -0.10344828]])

In [60]:
np.linalg.eig(newArr)

EigResult(eigenvalues=array([12.64025479, -0.44129134, -5.19896344]), eigenvectors=array([[-0.58510479, -0.93585469, -0.6976043 ],
       [-0.59005036,  0.35230532, -0.25671877],
       [-0.55632092, -0.00754775,  0.66891233]]))

In [68]:
xarr = np.array([[-1],[1],[2]])
print(xarr)

[[-1]
 [ 1]
 [ 2]]


In [69]:
np.linalg.solve( newArr,xarr)

array([[ 2.44827586],
       [-0.65517241],
       [-0.10344828]])